@startuml


start

:Команда CLI;

:Парсинг команды;

skinparam ConditionEndStyle hline

if (Все верно?) then (Да)
    :Чтение аргументов;

    :Выполнение команды из метода;

    :Формирование
     сообщения о
     результате
     выполнения;

else (Нет)

endif

:Сообщение;

:Вывод ответа в консоль ;


stop


@enduml
